services:
  laravel:
    container_name: laravel
    build: .
    volumes:
      - laravel_base:/usr/src/app
    expose:
      - "4444"
    networks:
      - server_default

volumes:
  laravel_base:

networks:
    server_default:
        name: server_default
        external: true