services:
  laravel:
    container_name: laravel
    build: .
    volumes:
      - laravel_base:/var/www/html
    ports:
      - "4444:80"
    networks:
      - server_default

volumes:
  laravel_base:

networks:
    server_default:
        name: server_default
        external: true